# Generated by Django 6.1.1 on 2026-09-23 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('path', models.TextField()),
                ('filename', models.CharField(max_length=512)),
                ('page_count', models.IntegerField()),
                ('last_processed_page', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('title', models.TextField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('review_log', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='content.document')),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_budget', models.IntegerField()),
                ('target_mcqs', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=32, null=True)),
                ('chunks_done', models.IntegerField(default=0)),
                ('questions_made', models.IntegerField(default=0)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='content.document')),
            ],
            options={
                'db_table': 'generation_runs',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('explanation', models.TextField()),
                ('source_pages', models.JSONField()),
                ('difficulty', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chunk')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.generationrun')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='quiz.quizset')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'page_start', 'page_end'), name='chunks_document_pages_uniq'),
        ),
    ]
