# Generated by Django 6.1.1 on 2026-09-24 04:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteScope',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scope', serialize=False, to='content.document')),
                ('selected', models.BooleanField(default=True)),
                ('page_from', models.IntegerField(default=1)),
                ('page_to', models.IntegerField(blank=True, null=True)),
                ('include_quiz', models.BooleanField(default=True)),
                ('include_reels', models.BooleanField(default=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_mtime', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'note_scopes',
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=16)),
                ('title', models.TextField()),
                ('storage_key', models.TextField()),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('source_pages', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='content.chunk')),
            ],
            options={
                'db_table': 'reels',
            },
        ),
    ]
