# Generated by Django 6.1.1 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_question_task_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='reels_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='key_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
