# Generated by Django 6.1.1 on 2026-09-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_newest_first_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reelview',
            index=models.Index(fields=['created_at'], name='reel_views_created_idx'),
        ),
    ]
