# Generated by Django 6.1.1 on 2026-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_question_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
