# Generated by Django 6.1.1 on 2026-09-25 16:03

from django.db import migrations, models


def not_uploaded_yet(apps, schema_editor):
    """Existing PDFs were read from a folder and have no stored copy: unavailable until the
    same PDF is uploaded, which reattaches it (same content hash) with all its progress."""
    apps.get_model("content", "Document").objects.filter(storage_key="").update(available=False)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_document_available_document_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.RemoveField(
            model_name='notescope',
            name='file_mtime',
        ),
        migrations.RemoveField(
            model_name='notescope',
            name='file_size',
        ),
        migrations.AddField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RunPython(not_uploaded_yet, migrations.RunPython.noop),
    ]
