# Generated by Django 6.1.1 on 2026-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_uploaded_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='stop_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
