# Generated by Django 6.1.1 on 2026-09-24 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_runs_per_day',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_tasks_per_run',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='pipeline_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='pipeline_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
