# Generated by Django 6.1.1 on 2026-09-24 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_pipeline_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='reel_limit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
