# Generated by Django 6.1.1 on 2026-09-24 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_reel_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('reels_watched', models.IntegerField(default=0)),
                ('questions_goal', models.IntegerField()),
                ('reels_goal', models.IntegerField()),
                ('questions_met', models.BooleanField(default=False)),
                ('reels_met', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_activity',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='daily_questions_goal',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='daily_reels_goal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['created_at'], name='quiz_attempts_created_idx'),
        ),
    ]
