# Generated by Django 6.1.1 on 2026-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizset_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notes_dir_reported',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
