# Generated by Django 6.1.1 on 2026-09-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_settings_notes_dir_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='pipeline_auto_cloud',
            field=models.BooleanField(default=False),
        ),
    ]
