# Generated by Django 6.1.1 on 2026-09-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_settings_pipeline_auto_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='notes_dir_reported',
        ),
    ]
