# Generated by Django 6.1.1 on 2026-09-30 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_uploaded_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='reel_limit',
        ),
        migrations.AddField(
            model_name='settings',
            name='questions_per_run',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='settings',
            name='reels_per_run',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
