# Generated by Django 6.1.1 on 2026-09-24 06:35

import django.db.models.deletion
import django.utils.timezone
import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_question_task_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('claude-session', 'Claude Session'), ('api-worker', 'Api Worker')], max_length=16)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'runners',
            },
        ),
        migrations.CreateModel(
            name='RunRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('reel', 'Reel')], max_length=16)),
                ('requested_by', models.CharField(default='app', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=pipeline.models._request_expiry)),
                ('consumed_by_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='content.generationrun')),
            ],
            options={
                'db_table': 'run_requests',
            },
        ),
    ]
