# Generated by Django 6.1.1 on 2026-09-26 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=16)),
                ('handle', models.CharField(max_length=200)),
                ('channel_id', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'followed_accounts',
                'constraints': [models.UniqueConstraint(fields=('platform', 'handle'), name='followed_accounts_platform_handle_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SocialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=16)),
                ('external_id', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('embed_url', models.URLField(max_length=500)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(choices=[('educational', 'Educational'), ('spam', 'Spam'), ('unsure', 'Unsure')], default='unsure', max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=16)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='social.followedaccount')),
            ],
            options={
                'db_table': 'social_videos',
            },
        ),
        migrations.CreateModel(
            name='SocialVideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('social_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='social.socialvideo')),
            ],
            options={
                'db_table': 'social_video_views',
            },
        ),
        migrations.AddIndex(
            model_name='socialvideo',
            index=models.Index(fields=['published_at'], name='social_videos_published_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialvideo',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='social_videos_platform_external_id_uniq'),
        ),
        migrations.AddIndex(
            model_name='socialvideoview',
            index=models.Index(fields=['created_at'], name='social_video_views_created_idx'),
        ),
    ]
